---

- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: Print installation message
    debug:
      msg: "Installing theHarvester..."

  - name: Clone theHarvester repository
    git:
      repo: https://github.com/laramies/theHarvester.git
      dest: /opt/theHarvester/  # Adjust path if needed
      force: yes  # Overwrite existing directory (optional)

  - name: Change directory to theHarvester
    fileglob:
      path: /opt/theHarvester/  # Adjust path if needed
      chdir: yes

  - name: Create virtual environment
    venv:
      name: /opt/theHarvester/theHarvester-venv  # Adjust path if needed

  - name: Activate virtual environment (using shell module)
    shell: source theHarvester-venv/bin/activate
    register: venv_activation  # Capture output for potential troubleshooting

  - name: Install dependencies using pip
    pip:
      requirements: /opt/theHarvester/requirements.txt  # Adjust path if needed
      virtualenv: /opt/theHarvester/theHarvester-venv  # Adjust path if needed

  - name: Deactivate virtual environment (using shell module)
    shell: deactivate
    when: venv_activation.rc == 0  # Deactivate only if activation was successful (optional)

  - name: Print success message (optional)
    debug:
      msg: "theHarvester Installed."
